sonar.projectKey=ZylosCore_bulkfolder
sonar.organization=zyloscore
sonar.sources=src
sonar.python.version=3.11

# Exclude assets and UI layouts from duplication checks to lower the 51.1% rate
sonar.cpd.exclusions=src/bulkfolder/ui/views/*.py

# Tell Sonar that we don't have coverage reports yet to avoid the 0% error
sonar.python.coverage.reportPaths=