name: Build and Release BulkFolder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller customtkinter matplotlib

    - name: Get version from XML
      id: get_version
      shell: powershell
      run: |
        [xml]$project = Get-Content "project_info.xml"
        $version = $project.project.version
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT

    - name: Build with PyInstaller
      run: |
        # Créez d'abord le fichier run.py comme discuté précédemment
        python -m PyInstaller --noconfirm --windowed --name "BulkFolder" --icon="src/assets/logo.ico" --add-data="src/assets;assets" --paths="src" --collect-all customtkinter run.py

    - name: Compile Inno Setup
      uses: rysoftware/inno-setup-action@v1
      with:
        filepath: installer_script.iss

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        name: Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          Output/*.exe  # Envoie l'installateur généré par Inno Setup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}